### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by revam**
I noticed a spelling mistake and proceeded to look through the whole read-me file. There are actually a lot of other less grammar related mistakes I would want to change, but I tried to keep it strictly to grammar mistakes… for now. The exception is the disclaimer that **should not** be hidden away in a scroll-able code block. You can hide it at the bottom of the section, but please don't try to hide it out of view.

### CODE REVIEW

**Comment by revam** [comment]
And now I don't know what @cla-bot is unhappy about. I'll leave this PR here for now.

**Comment by azukaar** [comment]
Hello! Sorry about cla-bot, he's is nice but not the sharpest tool in the shed.
Thanks for your contrib!
The ```sh should be ```bash, it's syntax highlighting
And the warning about portainer, I will keep it as `###` not as  `**` because it makes it bigger, and I want to make sure people see it

**Comment by revam** [comment]
> Hello! Sorry about cla-bot, he's is nice but not the sharpest tool in the shed.
Thanks for your contrib!

> I will keep it as ### not as ** because it makes it bigger, and I want to make sure people see it. Other than that, thanks!

I just want to point out that was previously #### and not ###, which is the same size as \*\*, except it also have a header link generated for it and uses \<h4\> instead of a normal \<p\> and also the reason why I changed it, to remove the link and switch it over to a **\<strong\>** \<p\>.

Also, thanks for stepping in for cla-bot. It's okay even if it's not the sharpest tool in the toolbox as long as we can compensate for its shortcomings. 😅

**Comment by azukaar** [comment]
> I just want to point out that was previously #### and not ###, which is the same size as **, except it also have a header link

Ah fair enough!!

**Pull request merged**
