### PR TITLE
Cosmos optimizations

### PR DESCRIPTION
**Pull request by Kawanaao**
Pull, so far only in the work stage

In this pull request, I plan to optimize the page loading speed as much as possible by optimizing bundles

|  Bundler  | Previous Full Size  | Current Full Size  | Previous Max File Size  | Current Max File Size |
| ------------- | -------------------------- | ------------------------  | -------------------------------  | ------------------------------- |
| WebPack |      5.6 MiB      |    4.2 MiB     |          4.1 MiB           |         3.3 MiB        |
|      Vite     |      4.3 MiB       |    4.7 MiB     |           3.3 MiB          |         3.7 MiB         |

I think that there are errors in this measurement, since there are additional installed libraries that affect the size of both WebPack and Vite, but they are related to WebPack and are necessary for debugging, so it is quite problematic to exclude them from the final sizes

### CODE REVIEW

**Comment by Kawanaao** [comment]
|  Bundler  | Previous Full Size  | Current Full Size  | Previous Max File Size  | Current Max File Size |
| ------------- | -------------------------- | ------------------------  | -------------------------------  | ------------------------------- |
| WebPack |      4.2 MiB     |    4.0 MiB     |          3.3 MiB           |         2.7 MiB        |
|      Vite     |      4.7 MiB       |    Err     |           3.7 MiB          |         Err         |

Changes:
* Added babel direct import plugin to reduce imported data, regardless of the code in the client
* Added long-term page hash caching
* Enabled code chunking to optimize overlapping libraries
* Added a debugging plugin - DuplicatesPlugin, necessary for analyzing duplicate dependencies for adding them to peerDependencies
* Replaced ts-loader with a single preset in Babel
* Many small changes related to existing settings

**Comment by azukaar** [comment]
Damn you've been working hard, looking forward to the complete PR :)
are you planning on removing Vite altogether? I'm ok with it, as long as the webpack does not take 10 min lol
Also if the demo build/dev still work ofc
Thanks for your work either way!

**Comment by Kawanaao** [comment]
Yeeey it works :D

image

**Comment by azukaar** [comment]
> Yeeey it works :D

well done haha

**Comment by Kawanaao** [comment]
Added myself as contributors @cla-bot check

**Comment by Kawanaao** [comment]
Since WebPack cannot understand what demo files are (which I told the web pack not to check at all in prod mode) i added a preprocessor for the code, perhaps you can also use it for something, rather than passing env variables and interpreting them in code

**Comment by azukaar** [comment]
oh no no you should have kept the env var, webpack doe not need to know what demo are, you just need to set the NODE_ENV to deom and let it rolland it will work

**Comment by Kawanaao** [comment]
> oh no no you should have kept the env var, webpack doe not need to know what demo are, you just need to set the NODE_ENV to deom and let it rolland it will work

Do you mean checking NODE_ENV instead of creating an additional process.env.isDemo? or abandon preprocessing in favor of leaving everything as it was?

**Comment by Kawanaao** [comment]
I think @cla-bot doesn't like me :0

**Comment by azukaar** [comment]
> Do you mean checking NODE_ENV instead of creating an additional process.env.isDemo? or abandon preprocessing in favor of leaving everything as it was?

Abandon preprocessing, I think it's an unnecessary additional component in the build pipeline

Remember that while I appreciate the work you are doing (I really do) simplicity is much MUCH more important than optimizing the bundle size, and that is why Vite was a nice options, with less than 10 lines of config everything was running smoothly. Remember once you're done optimizing, I still need to maintain this software afterward :)

**Comment by Kawanaao** [comment]
> > Do you mean checking NODE_ENV instead of creating an additional process.env.isDemo? or abandon preprocessing in favor of leaving everything as it was?
> 
> Abandon preprocessing, I think it's an unnecessary additional component in the build pipeline
> 
> Remember that while I appreciate the work you are doing (I really do) simplicity is much MUCH more important than optimizing the bundle size, and that is why Vite was a nice options, with less than 10 lines of config everything was running smoothly. Remember once you're done optimizing, I still need to maintain this software afterward :)
> 
> (also about BCrypt you cannot remove it it has to be BCrypt for OpenID to work)

Thank you for your nice words, glad to help :)

I removed preprocessing, it’s really not needed, since you can replace it with a regular check with process.env.NODE === “demo” and treeshaking will automatically remove all unnecessary imports

As for modules - it’s scary to touch them, JS after 6 years of development on TS without JS seems like something like assembler :D

**Comment by Kawanaao** [comment]
I think it can be fixed by simply removing the first message update call, or by forcing the server to respond to such messages correctly

image

**Comment by Kawanaao** [comment]
Can I ask for further help? since I can’t do much more, optimizations work, in demo mode, in release mode, the development server works fine, but the backend refuses to work

1. Tried to launch => backend replied that a new installation was needed
2. I switched to a new installation - at the stage of creating the database everything died with the error assignment to entry in nil map in Networks
3. I fixed this error by making the Networks declaration, but then the backend simply did not find the database, with the error cosmos-mongo-BGj:27017 ... cannot lookup on 192.168.1.1:53: no such host, cosmos created the network, but remained on bridge

I can’t check because of these errors, do you have any ideas what I’m doing wrong?

**Comment by Kawanaao** [comment]
For now - I think everything is working perfectly, without a cache, loading a page takes about 20 kb of traffic without caching, excluding the market page, when the unstable is ready - I will do a rebase on it, now the stable one is being used to check the overall operation of the cosmos server

**Pull request closed without merging**
